### ISSUE TITLE
Manage all @Ignored tests

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#356] opened 2016-10-03 10:56 UTC
Move them to `Issue` files, which may or may not be `@Ignore`. If there is no issue, open one

**Comment by yossigil** [comment] 2016-10-04 14:35
There is a huge mess with tests which were ignored in the rush towards the submission. The mission here is to restore order in these. The following steps are required:
1. Enable all `@Ignore` tests, and take note that all tests that fail (this may be a little less than 100).
2. All tests which can be fixed by changing the input/output, should be fixed, provided that this change is in accordance with the desired behavior, e..g, #335 
3. The remaining tests should be made into issues:
  - Create an issue in git hub, 
  - Label it `folks` and `bug`
  - Deadline should be version 2.65
  - Assignee should be empty
4. After creating the issue, create a test class numbered IssueXXX, and move all the failing tests into that class. Move and don't copy.
5. Tag the test class with `@Ignore`, and remove the `@Ignore` from all methods
6. Commit the class using `#XXX` in the commit message
7. Start with the easy cases, open issues for me, when you are not clear.

-

**Comment by dngreenst** [comment] 2016-10-08 10:12
Current status: 
45 skipped when running JUnit.
Of those: 

New issues and new test classes: #411, #410, #415.
Old open issues, with new test classes: #115, #20, #76.
Existing test classes with open issues, and a very high rate of test failure: #230 (14/22 tests), #249 (9/10), #390 (1/1).

The others are cases in which I thought that moving the tests will cause more harm than good, because I think they are actively developed at the moment, or because removing them will remove context that is important. Those are:
EnvironmentTest - responsible for 22/45 of the skips.
TestFactoryTest - 1 skipped.
InfixIndexOfToStringContainsTest - 3/4 are skipped.
LogManagerTest - 3/7 skipped.
LeonidasTest - 2/22 skipped.
TrimmerLogTest - 3/6 skipped.
Issue408 - The whole class is ignored, I believe it is under development. 
IgnoredTrimmerTest - ignored, as it is meant to be.

@orimarco , @M4tt30rru , @OriRoth  - Can you confirm that TestFactoryTest , InfixIndexOfToStringContainsTest , LogManagerTest , LeonidasTest , TrimmerLogTest  are being developed?

**Comment by M4tt30rru** [comment] 2016-10-08 10:51
@dngreenst I can confirm Issue408 is under development.
I think the LogManager is going to be removed because there other (better) classes that have the same functionalities. Let me have a look at it.

**Comment by dngreenst** [comment] 2016-10-09 20:06
17 skipped, all of them classes. Closing.

**Closed by dngreenst** 2016-10-09 20:06 UTC
Labels: Quality assurance

**Comment by yossigil** [comment] 2016-10-10 05:02
:100:
