### ISSUE TITLE
Constructor Rename arguments goes into infinite loop

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1259] opened 2017-04-19 19:26 UTC
The bug is in AssignmentAndAssignmentOfSameValue:
```
<M extends AccessibleObject & Member> Element(M accessibleObject) {
    checkNotNull(accessibleObject);
    this.accessibleObject = accessibleObject;
    this.member = accessibleObject;
  }
```
goes to
```
<M extends AccessibleObject & Member> Element(M member) {
    checkNotNull(member);
    this.accessibleObject = member;
    this.member = member;
  }
```
then goes to
```
<M extends AccessibleObject & Member> Element(M accessibleObject) {
    checkNotNull(accessibleObject);
    this.accessibleObject = accessibleObject;
    this.member = accessibleObject;
  }
```
(same code as before)
and so on in infinite loop.

**Comment by OriRoth** [comment] 2017-04-19 20:58
This is an architectural flaw. It would be dealt with by @dormaayan eventually. In the meanwhile, there are the following options:
* Disable one of the tippers
* Ignore the problem (my recommendation)
* Review naming mechanism- nowadays, naming tippers says whether a name is *bad* (can apply to it) or *natural* (cannot apply to it), but not whether the name is *good*... if they would be able to do so, we can ignore such names in `Traversal`. This mechanism can be further generalized if needed.

**Comment by yossigil** [comment] 2017-04-20 05:35
Ori seems to understand the problem, but I can't. Yuval, if you create a unit test I will fix it in no time

**Comment by yuvalsimon** [comment] 2017-04-20 10:33
I created a unit test already (Issue1259). You can see that it loops for ever, tips to the above codes alternately.

**Comment by yossigil** [comment] 2017-04-20 19:34
The bug is with `ConstructorRenameParameters`, written by @dormaayan. 
The problem is unrelated to assignment, but to the fact that in this case:
```java
Ctor(int a) {this.a=a;this.b=a;}
```
it offers to replace 'b' with 'a' and then back again. Because in both cases, it looks as if it assigns a parameter to a field. To fix:

- [ ] Make a function in class 'compute' to retrieve all assignment to fields statements in a method, using map reduce.
- [ ] Make a tournament. If a field has more than parameter assigned to it, or if a parameter assigned to more than one field, there is a conflict.

@dormaayan, can you take it, or would you like me to pursue it?
If you are at it, you may want to think of setters.

**Closed** 2017-04-22 05:32 UTC
Labels: bug
