### ISSUE TITLE
Centification failure with try/catch?

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#464] opened 2016-10-17 10:57 UTC
Not sure that this is the reason, but here is the input

``` java
  /** @param f
   * @return
   * @throws CoreException */
  private static IMarker[] getMarkers(final IFile f) {
    try {
      return f.findMarkers(Builder.MARKER_TYPE, true, IResource.DEPTH_INFINITE);
    } catch (CoreException x) {
      monitor.log(x);
      return new IMarker[0]; 
    }
  }
```

I get a suggestion, but it cannot be implemented.

**Comment by OriRoth** [comment] 2016-11-25 11:53
I think it is fine now. This code is from our project (`SpartanMovie.java`). The current code does not offer a spartanization because the parameter was changed to `¢`. If I change the parameter name back to `f` and try to spartanize the file in debug mode then I get a catch renaming suggestion that works.
@kfir-marx please confirm this using #425 and close the issue.

**Comment by kfir-marx** [comment] 2016-11-25 12:24
I'm on it.

**Comment by kfir-marx** [comment] 2016-11-25 13:01
confirmed no bug.
in debug mod I changed to code above  , and got a catch parameter renaming suggestion to ¢.

**Closed by kfir-marx** 2016-11-25 13:01 UTC
Labels: bug, Rename a name

**Comment by yossigil** [comment] 2016-11-25 13:40
:+1:
