### ISSUE TITLE
Nest markers by category

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#248] opened 2016-09-23 20:51 UTC
http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_core_resources_markers.html

**Comment by yossigil** [comment] 2016-11-01 08:32
@OriRoth : FYI

**Comment by OriRoth** [comment] 2017-04-03 10:48
Duplicate of #471

**Closed by OriRoth** 2017-04-03 10:48 UTC
Labels: Architecture, maintenance, On hold, Quality assurance
