### ISSUE TITLE
Early return from functions

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#194] opened 2016-09-13 21:39 UTC
There is something that does this, but it cannot handle

``` java
if (a != null) {
   final a = f(); 
    if (g());
        return f();
    if (f() && g())  {
        return a; 
   }
}
return null;
```

wring to:

``` java
if (a == null) 
   return null;

final a = f(); 
if (g());
   return f();
 if (f() && g())  {
    return a; 
 }
}
return null;
```

**Comment by yossigil** [comment] 2016-09-14 05:12
- [ ] Create several test cases. At which length do we want the spartanization
- [ ] Make sure the tests fail!. Commit them, with a `@Ignore` label. The commit message should include a reference to the issue.
- [ ] Find the wring that does this.
- [ ] If there is none, create your own wring.
- [ ] Make sure the tests pass.
- [ ] Spartanize the code of the plugin using using your own wring
- [ ] Spartanize another project with your wring.
- [ ] Open issue(s), as per problems you encounter
- [ ] Perfect your wring, by adding test cases for any problems your encounter
- [ ] Commit your fix, using `Fix #194` in the commit message.
- [ ] Make sure that the commit indeed closed this issue.

**Comment by yossigil** [comment] 2016-09-14 05:14
@dngreenst / @sakopzon : you may want to try this. It is mundane, but the detailed instructions, might come in handy at some other case. Talk to me.

**Comment by dngreenst** [comment] 2016-09-15 14:37
What should the wring itself do? I do have a general idea from the issue's title, but not a concrete one. Could you add a before and after example, please?

**Comment by yossigil** [comment] 2016-09-15 16:04
Edited the documentation

**Comment by dngreenst** [comment] 2016-09-15 22:39
The wring that does this is `IfCommandsSequencerNoElseSingletonSequencer()`. 

At the moment, I believe that the issue is that `endsWithSequencer()`'s check is not general enough.

The method only checks that the last statement is a sequencer. Statements that do end with sequencers, but wrap these sequencers with other statements, will return false.

For example: 

`{x=5; if(y>x) return a; else {z=6; return b;}}` will return false.

**Comment by yossigil** [comment] 2016-09-16 05:29
Good job! But, only keep to it if you enjoy it.

**Comment by dngreenst** [comment] 2016-09-16 09:16
I think I'd rather see this through. Might not find the time until Sunday evening, however.

**Comment by yossigil** [comment] 2016-09-16 10:46
As you wish. This is not a blocker in any way.

**Comment by yossigil** [comment] 2016-09-21 18:27
This is all a matter of writing a method (say in class `iz`), that will check if a statement is last in function. 
I vaguely remember that I did this some time ago. Perhaps there is a threshold?

**Comment by yossigil** [comment] 2016-09-22 05:51
What's up?

**Comment by dngreenst** [comment] 2016-09-22 06:21
Will be done today.

**Comment by dngreenst** [comment] 2016-09-22 09:43
@yossigil to the best of my understanding, we wring for an early `return` only if we know for certain that the `ifstatement` will end with a sequencer. If that is the case, we know for certain that either the `ifstatement`'s `then` or the `return` will be executed, but never both. 

I have improved the logic that detects this, and I will test it further.

However, it seems that the example in issue's description does not fit the bill. We might want to execute the outer `ifstatement`'s `then` and still use the outside `return null`. There is no guarantee that the inside sequencers will be triggered.

**Comment by yossigil** [comment] 2016-09-22 11:13
Not sure  I understand. I will take a look when it is done.

**Comment by yossigil** [comment] 2016-09-25 00:06
Pending on #249

**Comment by yossigil** [comment] 2017-01-15 13:06
@tomerdragucki what's up?

**Comment by OriRoth** [comment] 2017-03-24 15:06
See 8532813767b448575349e070d8587aeaf3ef8a50. My solution is to "normalize" the then section of the if statement, i.e. if it is a block that does *not* end with a sequencer, we add the following sequencer (i.e. `nextStatement`) to it. Changes to `IfCommandsSequencerNoElseSingletonSequencer`:
```Java
    if (!iz.vacuousElse(s) || !iz.sequencer(nextStatement) || !wizard.endsWithSequencer(then(s)))
      return null;
    final IfStatement asVirtualIf = subject.pair(then(s), nextStatement).toIf(s.getExpression());
...
```
==>
```Java
    if (!iz.vacuousElse(s) || !iz.sequencer(nextStatement) || !iz.sequencer(then(s)) && !iz.block(then(s)))
      return null;
    final IfStatement asVirtualIf = subject.pair( //
        !(then(s) instanceof Block) || wizard.endsWithSequencer(then(s)) ? then(s)
            : subject.ss(extract.statements(az.block(then(s)))).add(copy.of(nextStatement)).toBlock(), //
        nextStatement //
    ).toIf(s.getExpression());
```

Now the test case from the first comment of this thread is passing.

@yossigil please confirm this is OK so I can fix failing tests (only 3) and close the issue.

**Comment by yossigil** [comment] 2017-03-24 15:19
Sure. go ahead

**Closed** 2017-03-24 15:50 UTC
Labels: CFG, enhancement, new-tipper
