### ISSUE TITLE
Bug in LongIfExpander

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1092] opened 2017-01-19 00:25 UTC
It gets to infinite loop, try to run it on enumerate.java class (in tdd package).

* This bug is inherited in the essence of this Bloater, see discussion below.

**Comment by mdoron** [comment] 2017-03-21 17:07
@yuvalsimon Yuval I cannot reproduce this problem, it seems like this LongIfBloater just doesn't do anything. Can you give me a hand in reproducing the problem?

**Comment by OriRoth** [comment] 2017-03-21 17:11
@mdoron did you run it on `enumerate.java`? Did you confirmed it does not stuck in a loop?

**Comment by mdoron** [comment] 2017-03-21 17:37
@OriRoth  yes, I did, and it just does't do anything. Would you like to check it yourself? Yuval says it suppose to over-bloat until limit of permitted line number;

**Comment by mdoron** [comment] 2017-03-21 18:35
OK I'm closing until someone can reproduce this issue, @yuvalsimon reopen this if you can.

**Comment by OriRoth** [comment] 2017-03-21 18:47
Yuval has given you enough information. When zooming `enumerate.java` with `LongIfExpander` in the `InflaterProvider` I get multiple `java.lang.IllegalArgumentException`, check it out. Be sure you are zomming the entire file at once, by clicking on the file in the package explorer then type `ctrl + alt + d`.

**Comment by mdoron** [comment] 2017-03-21 18:54
@OriRoth I got it too, but I didn't get the infinite loop he was talking about so this is problem is for another issue. I tried to investigate this problem also and am about to open different issue for it.

**Comment by mdoron** [comment] 2017-03-21 19:51
@tomerdragucki, logically, does this bloater must duplicate code? Why
```
if(a && b) { 
    do1();
} else {
    do2();
}
```
becomes
```
if (a)
	if (b)
		do1();
	else {
		do2();
	}
else {
	do2();
}
```
and not
```
if (a)
	if (b)
		do1();
else {
	do2();
}
```
?

**Comment by OriRoth** [comment] 2017-03-21 20:09
The first two options are logically equivalent. The third is not equivalent to them.

**Comment by mdoron** [comment] 2017-03-21 21:19
So it seems like the only solution is to extract the `else` code into a void function, and then we avoid duplicating large codes, but create new functions which is not a necessarily a wanted behavior.

@tomerdragucki, I'm letting you call on this one, you should decide whether to eliminate this Bloater or implementing my solution (or better solution).

**Comment by yuvalsimon** [comment] 2017-03-24 14:30
Ok it actually seems to work fine. The problem is that it has to duplicate else statements, for example
```
if(a && b) $=1;
else $=2;
```
goes to
```
if(a) { if(b) $=1; else $=2; }
else $=2;
```
The problem in enumerate.java is that there is a long if-else statemet in the following structure:
```
if (true && true) {} 
else if (true && true && true) { } 
else if ((true || true) && true && true) {} 
else if (true && true && true) {} 
else if ((true || true) && true) {} 
else if (true && true) {} 
else if (true && true && true) {} 
else if (true && true && true) {} 
else if (true && true && (true || true)) {}
```
and after first expansion
```
if (true && true) {} 
 else {
      if (true && true&& true) {}
      else if ((true || true) && true && true) {} 
      else if (true && true && true) {}
      else if ((true || true) && true) {} 
      else if (true&& true) {} 
      else if (true && true && true) {} 
      else if (true && true && true) {} 
      else if (true && true && (true || true)) {}
 }
```
Then the else block is duplicated as in the example above, so it grows exponentially to about 17000 lines!
I think we should avoid expanders that duplicate whole blocks. What do you think @OriRoth ?

**Comment by OriRoth** [comment] 2017-03-24 15:18
Yeah I talked with Doron about it... this bloater should be removed, or at least limited by some heuristic.

**Comment by mdoron** [comment] 2017-03-24 17:43
@yuvalsimon read my comment above yours, I think we'll keep this bloater out of the toolbox for now, and the original author of it will try to fix it.

**Comment by yuvalsimon** [comment] 2017-03-24 22:58
I see, I missed it somehow. So Tomer will decide what to do.

**Comment by tomerdragucki** [comment] 2017-04-08 20:16
I limited the number of cases in which the bloater will work. In case both take place: there's an else clause and the InfixExpression has more than two arguments- the bloater won't be activated.

**Closed** 2017-04-08 20:27 UTC
Labels: bug
