### ISSUE TITLE
Renaming to cent lambda problem

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#499] opened 2016-10-21 11:27 UTC
Consider these two methods:

```
  /** Default run action configuration of {@link Spartanizer}. Spartanize the
   * {@link ICompilationUnit} using received {@link GUI$Applicator}.
   * @param a JD
   * @return this applicator */
  public Spartanizer defaultRunAction(final GUI$Applicator a) {
    assert a != null;
    runAction(¢ -> Integer.valueOf(a.apply(¢, selection())));
    return this;
  }

  /** Default name configuration according to used {@link GUI$Applicator}.
   * @param a JD
   * @return this applicator */
  public Spartanizer defaultName(final GUI$Applicator a) {
    assert a != null;
    name(a.name());
    return this;
  }
```

Renaming to cent is offered only for the second method. I get a suggestion for the first one as well if I remove the lambda expression:

```
  /** Default run action configuration of {@link Spartanizer}. Spartanize the
   * {@link ICompilationUnit} using received {@link GUI$Applicator}.
   * @param a JD
   * @return this applicator */
  public Spartanizer defaultRunAction(final GUI$Applicator a) {
    assert a != null;
    runAction(/*¢ -> Integer.valueOf(a.apply(¢, selection()))*/);
    return this;
  }
```

**Comment by OriRoth** [comment] 2016-10-21 11:28
May be a duplication of another issue though....

**Comment by yossigil** [comment] 2016-10-21 12:13
Yes, this was rasied  #121

**Comment by OriRoth** [comment] 2016-10-21 12:57
Cool, but #121 is closed so I will keep this open (the problem still exists).

**Comment by yossigil** [comment] 2016-11-17 07:41
@dormaayan please assign to one or more team members

**Comment by dormaayan** [comment] 2016-11-17 07:48
@kobybs :
I assigned you for that, if you need any help feel free to talk to me here

**Comment by dormaayan** [comment] 2016-11-17 14:49
@yossigil : 
I found the "bug" here :
At the tipper `MethodDeclarationRenameSingleParameterToCent`, we do the check before we do the renaming that there isn't any Variable Definition in the block of the function, but, According to the documentation of LambdaExpression :

> The first two forms use VariableDeclarationFragment for the parameter or parameters, while the third form uses SingleVariableDeclaration.

So, what do you think we should do here ? Do we really want to do the renaming in that case ?

**Comment by yossigil** [comment] 2016-11-17 16:33
I am not sure I understand the difference. We should not make overloaded names.

**Comment by dormaayan** [comment] 2016-11-17 16:35
@yossigil :
I know, the example here is not good beacause there is overloading on cent but I talk about the following case :

`  public Spartanizer defaultRunAction(final GUI$Applicator a) {
    assert a != null;
    runAction(x -> Integer.valueOf(a.apply(x, selection())));
    return this;
  }`

here I would expect for renaming but there isn't anyone because of the reasons I explained above

**Comment by OriRoth** [comment] 2016-11-17 16:52
@dormaayan I do not understand your example - `a` is considered a `SimpleName`, not a `Variableeclaration` or whatever.

**Comment by OriRoth** [comment] 2016-11-17 16:57
OK I think I got it... in my opinion, the best solution would be *ignoring lambda variable definitions* if, and only if, their name is not ¢.
Notice we cannot simply ignore lambda expressions.

**Comment by dormaayan** [comment] 2016-11-17 16:57
thats right, but, if you look at the code of the tipper itself it does contain a check that there isn't any variable declaration in the block of the function, the problem is that lambda expression contain variable declaration inside and because of that the tipper isn't work on that cases.
My question is, should we cancel that restriction (over block with variable declaration) or not ?

**Comment by OriRoth** [comment] 2016-11-17 16:59
We can supply a fix specifically for lambda variable definitions, by checking the parent type of the variable declarations.

**Comment by dormaayan** [comment] 2016-11-17 16:59
@OriRoth  @yossigil :
I konw that Ori, but can't we generalize that to all variable declerations ?

**Comment by OriRoth** [comment] 2016-11-17 17:01
Well... I believe there was a purpose for this, probably conceptual more than practical... Its up to @yossigil now I guess. But good job @dormaayan take this +5 Karma you deserve it.

**Comment by dormaayan** [comment] 2016-11-20 09:44
@yossigil :
Can I close that Issue ?

**Comment by yossigil** [comment] 2016-11-20 09:49
Still, did not get a chance to fully understand this. I will close it for now, trusting you.
I mean, I understand the problem, but I am not sure I understand the alternatives. IMHO, cent should be used in the smallest context possible. but what do I know, and I am not sure I understand what each one of you is arguing

**Closed by yossigil** 2016-11-20 09:49 UTC
Labels: bug, Folks, On hold, Rename a name

**Comment by dormaayan** [comment] 2016-11-20 09:51
@yossigil :
Personally, I think that the alternative here is to keep the situation like that, and thats match to your concept of 

> cent should be used in the smallest context possible

thanks !
