### ISSUE TITLE
Convert GUI issue #429 into a wiki page.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#472] opened 2016-10-19 06:24 UTC
#429

**Comment by OriRoth** [comment] 2016-10-19 07:52
I have written a usage tutorial: https://github.com/SpartanRefactoring/Spartanizer/wiki/Tutorial
It needs to be updated.

**Comment by yossigil** [comment] 2016-10-19 15:48
OK, this will be the job of the GUI/IT team of folks

**Comment by OriRoth** [comment] 2017-04-08 09:29
Duplicate of #1210

**Closed by OriRoth** 2017-04-08 09:29 UTC
Labels: Architecture
