### ISSUE TITLE
Inline for loop parameter delay

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#213] opened 2016-09-15 10:09 UTC
@yossigil rename, reassign (me?). This bug does not fail the spartanization process.
```
for (Throwable e : fErrors) {
  sb.append(String.format("\n  %s(%s)", e.getClass().getName(), e.getMessage()));
}
```
When spartanized using "spartanize all" or "spartanize file", the plugin tries to run both "rename cent" and "block singleton" on the for loop. The problem is that "rename cent" is called first, sees `Throwable e` and changes for loop to
```
for (Throwable ¢ : fErrors) {
  sb.append(String.format("\n  %s(%s)", ¢.getClass().getName(), ¢.getMessage()));
}
```
"block singleton" is called second, sees
```
{
  sb.append(String.format("\n  %s(%s)", e.getClass().getName(), e.getMessage()));
}
```
and changes to `sb.append(String.format("\n  %s(%s)", e.getClass().getName(), e.getMessage()));`. So the final result is:
```
for (Throwable ¢ : fErrors) {
  sb.append(String.format("\n  %s(%s)", e.getClass().getName(), e.getMessage()));
}
```
Which does not compile (unrecognized variable `e`). There may be several solutions, we should decide how exactly to solve it.
**The problem in other words: a wring that changes code outside marker.**
Moreover, it can be problematic to test it! the current test methodology we use does not cover it.

**Comment by OriRoth** [comment] 2016-09-15 10:12
Simpler example:
```
for (X x : xs) {
  x.f();
}
```
==spartanize active window==>
```
for (X ¢ : xs)
  x.f();
```

**Comment by yossigil** [comment] 2016-09-15 16:09
- The abbreviate name should never be applied if the name is ¢
- I never knew we abbreviated anything but parameter names. I never knew we could do that for loop variables. Did I miss something? It is of course nice.
- I trust some of the problem is with centification of foreach. To increase the marked range, you should first match on the FOR LOOP, and then pass on to functio `make` (now called `suggest`) all involved nodes. Function `make/suggest` computed the union of these.

**Comment by OriRoth** [comment] 2016-09-15 16:40
There is a wring for renaming for loop parameter. The problem is a wring that changes code outside it's marked area: that's causing the rewrite of BlockSingleton to override the parameter name rewrite:
```
// original
for (X x : xs) {
  x.f();
}
```
```
// abbreviate name
for (X ¢ : xs) {
  ¢.f();
}
```
```
// block singleton
for (X x : xs)
  x.f();
```
Both of the wrings are conducted simultaneously with "spartanize entire project" or "spartanize active window": first cent rename then block singleton (by visiting order).
```
// spartanization result
for (X ¢ : xs)
  x.f();
```
We got a rewrite override. `x` is unrecognized (r worse, recognized).

**Comment by yossigil** [comment] 2016-09-15 20:14
I thought exclude was supposed to take care of this... Yuk.

**Comment by OriRoth** [comment] 2016-09-15 20:17
Yes, using the excluder is the best way... reassign the issue

**Comment by yossigil** [comment] 2016-09-18 08:24
Reassigned

**Comment by yossigil** [comment] 2016-09-21 18:22
@OriRoth : I think I largely solved this. Reopen if necessary.

**Closed by yossigil** 2016-09-21 18:22 UTC
Labels: bug
