### ISSUE TITLE
Exceptions from RenameShortNamesMethodDec

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1109] opened 2017-01-22 19:55 UTC
It throws lots of exceptions. Do not add it to the release please, not enough time to make sure it works until tomorrow...

**Comment by yuvalsimon** [comment] 2017-01-22 20:03
See #1108

**Comment by ravivos** [comment] 2017-01-22 21:46
you are right.
Im taking it out of the toolbox but I think that the problem is in the name generation though
#1044

**Comment by ravivos** [comment] 2017-01-22 22:01
I think it's a duplicate of #1100, don't you?
@yuvalsimon if so, close this issue

**Comment by yuvalsimon** [comment] 2017-01-22 22:02
@ravivos keep this open until it's solved. I'm not sure what causes there, I think you should wait for #1008 and use it, then it would be easier to check this.

**Comment by yuvalsimon** [comment] 2017-01-22 22:04
Yes it's a duplicate, I closed #1100. I thought it was closed already..

**Comment by yuvalsimon** [comment] 2017-01-22 22:16
@ravivos I implemented the method for #1008, you can use it. Checkout my last commit. It still has the problem I mentioned in #1044, so this should work well only when using the wheel. If you finish this issue check that all the errors you get when debugging are of the type in #1044.

**Comment by ravivos** [comment] 2017-01-23 18:50
will be fixed.
for Now, this expander is out of use

**Closed** 2017-04-26 01:11 UTC
Labels: bug, On hold
