### ISSUE TITLE
Operation assignment to non assignment with operator

### ISSUE THREAD

**Issue by mdoron** [SpartanRefactoring/Spartanizer#1001] opened 2016-12-23 22:11 UTC
Convert
``` x #= exp; ```
to
``` x = x # exp;```
where # can be any operator.

**Comment by tomerdragucki** [comment] 2016-12-23 22:39
#973

**Comment by mdoron** [comment] 2016-12-23 23:05
thanks

**Comment by yossigil** [comment] 2016-12-27 12:30
@tomerdragucki : if you did it, then make sure it shows that you are the assignee

**Comment by tomerdragucki** [comment] 2016-12-28 00:47
@yossigil This issue is a duplicate of an expander idea that @OriRoth implemented.

**Comment by yossigil** [comment] 2017-04-27 17:30
Tests are failing

**Comment by yuvalsimon** [comment] 2017-04-27 18:44
Fixed it already, my commit was reverted

**Closed** 2017-04-27 18:44 UTC
Labels: new-zoomer
